version: "3.3" 

services:
  go_wa_rest:
    build: .
    container_name: go_wa_rest
    ports:
      - "8080:8080"
    environment:
      ENV: development
      APP_TIMEOUT: 20
      SERVER_PORT: 8080
      WHATSAPP_DATASTORE_TYPE: sqlite
      WHATSAPP_DATASTORE_URI: file:dbs/WhatsApp.db?_foreign_keys=on
      JWT_SECRET: spidermansecret
