// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "go_wa_rest/domain/entity"
	exceptions "go_wa_rest/pkg/exceptions"

	mock "github.com/stretchr/testify/mock"

	types "go.mau.fi/whatsmeow/types"
)

// WhatsAppUseCase is an autogenerated mock type for the WhatsAppUseCase type
type WhatsAppUseCase struct {
	mock.Mock
}

// GetGroup provides a mock function with given fields: ctx
func (_m *WhatsAppUseCase) GetGroup(ctx context.Context) ([]*types.GroupInfo, *exceptions.CustomerError) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 []*types.GroupInfo
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context) ([]*types.GroupInfo, *exceptions.CustomerError)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*types.GroupInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.GroupInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *exceptions.CustomerError); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// GetGroupV2 provides a mock function with given fields: ctx, jid
func (_m *WhatsAppUseCase) GetGroupV2(ctx context.Context, jid string) ([]*types.GroupInfo, *exceptions.CustomerError) {
	ret := _m.Called(ctx, jid)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupV2")
	}

	var r0 []*types.GroupInfo
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*types.GroupInfo, *exceptions.CustomerError)); ok {
		return rf(ctx, jid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*types.GroupInfo); ok {
		r0 = rf(ctx, jid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.GroupInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *exceptions.CustomerError); ok {
		r1 = rf(ctx, jid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// GetMessageStatus provides a mock function with given fields: ctx, whatsAppStatus
func (_m *WhatsAppUseCase) GetMessageStatus(ctx context.Context, whatsAppStatus *entity.WhatsAppStatus) (*entity.WhatsAppStatus, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsAppStatus)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageStatus")
	}

	var r0 *entity.WhatsAppStatus
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppStatus) (*entity.WhatsAppStatus, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsAppStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppStatus) *entity.WhatsAppStatus); ok {
		r0 = rf(ctx, whatsAppStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsAppStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsAppStatus) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsAppStatus)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// GetMessageStatusV2 provides a mock function with given fields: ctx, whatsAppStatus, jid
func (_m *WhatsAppUseCase) GetMessageStatusV2(ctx context.Context, whatsAppStatus *entity.WhatsAppStatus, jid string) (*entity.WhatsAppStatus, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsAppStatus, jid)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageStatusV2")
	}

	var r0 *entity.WhatsAppStatus
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppStatus, string) (*entity.WhatsAppStatus, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsAppStatus, jid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppStatus, string) *entity.WhatsAppStatus); ok {
		r0 = rf(ctx, whatsAppStatus, jid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsAppStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsAppStatus, string) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsAppStatus, jid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// GetQr provides a mock function with given fields: ctx
func (_m *WhatsAppUseCase) GetQr(ctx context.Context) (string, int, *exceptions.CustomerError) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQr")
	}

	var r0 string
	var r1 int
	var r2 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context) (string, int, *exceptions.CustomerError)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) *exceptions.CustomerError); ok {
		r2 = rf(ctx)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*exceptions.CustomerError)
		}
	}

	return r0, r1, r2
}

// GetQrV2 provides a mock function with given fields: ctx, jid
func (_m *WhatsAppUseCase) GetQrV2(ctx context.Context, jid string) (string, int, *exceptions.CustomerError) {
	ret := _m.Called(ctx, jid)

	if len(ret) == 0 {
		panic("no return value specified for GetQrV2")
	}

	var r0 string
	var r1 int
	var r2 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, int, *exceptions.CustomerError)); ok {
		return rf(ctx, jid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, jid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, jid)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) *exceptions.CustomerError); ok {
		r2 = rf(ctx, jid)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*exceptions.CustomerError)
		}
	}

	return r0, r1, r2
}

// Logout provides a mock function with given fields: ctx
func (_m *WhatsAppUseCase) Logout(ctx context.Context) *exceptions.CustomerError {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context) *exceptions.CustomerError); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exceptions.CustomerError)
		}
	}

	return r0
}

// LogoutV2 provides a mock function with given fields: ctx, jid
func (_m *WhatsAppUseCase) LogoutV2(ctx context.Context, jid string) *exceptions.CustomerError {
	ret := _m.Called(ctx, jid)

	if len(ret) == 0 {
		panic("no return value specified for LogoutV2")
	}

	var r0 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, string) *exceptions.CustomerError); ok {
		r0 = rf(ctx, jid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exceptions.CustomerError)
		}
	}

	return r0
}

// SaveContactV2 provides a mock function with given fields: ctx, jid, msisdn, fullName, firstName
func (_m *WhatsAppUseCase) SaveContactV2(ctx context.Context, jid string, msisdn string, fullName string, firstName string) *exceptions.CustomerError {
	ret := _m.Called(ctx, jid, msisdn, fullName, firstName)

	if len(ret) == 0 {
		panic("no return value specified for SaveContactV2")
	}

	var r0 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *exceptions.CustomerError); ok {
		r0 = rf(ctx, jid, msisdn, fullName, firstName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exceptions.CustomerError)
		}
	}

	return r0
}

// SendDocument provides a mock function with given fields: ctx, whatsAppDocument
func (_m *WhatsAppUseCase) SendDocument(ctx context.Context, whatsAppDocument *entity.WhatsAppDocument) (*entity.WhatsAppDocument, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsAppDocument)

	if len(ret) == 0 {
		panic("no return value specified for SendDocument")
	}

	var r0 *entity.WhatsAppDocument
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppDocument) (*entity.WhatsAppDocument, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsAppDocument)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppDocument) *entity.WhatsAppDocument); ok {
		r0 = rf(ctx, whatsAppDocument)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsAppDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsAppDocument) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsAppDocument)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// SendDocumentV2 provides a mock function with given fields: ctx, whatsAppDocument, jid
func (_m *WhatsAppUseCase) SendDocumentV2(ctx context.Context, whatsAppDocument *entity.WhatsAppDocument, jid string) (*entity.WhatsAppDocument, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsAppDocument, jid)

	if len(ret) == 0 {
		panic("no return value specified for SendDocumentV2")
	}

	var r0 *entity.WhatsAppDocument
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppDocument, string) (*entity.WhatsAppDocument, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsAppDocument, jid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppDocument, string) *entity.WhatsAppDocument); ok {
		r0 = rf(ctx, whatsAppDocument, jid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsAppDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsAppDocument, string) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsAppDocument, jid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// SendImage provides a mock function with given fields: ctx, whatsAppImage
func (_m *WhatsAppUseCase) SendImage(ctx context.Context, whatsAppImage *entity.WhatsAppImage) (*entity.WhatsAppImage, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsAppImage)

	if len(ret) == 0 {
		panic("no return value specified for SendImage")
	}

	var r0 *entity.WhatsAppImage
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppImage) (*entity.WhatsAppImage, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsAppImage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppImage) *entity.WhatsAppImage); ok {
		r0 = rf(ctx, whatsAppImage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsAppImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsAppImage) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsAppImage)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// SendImageV2 provides a mock function with given fields: ctx, whatsAppImage, jid
func (_m *WhatsAppUseCase) SendImageV2(ctx context.Context, whatsAppImage *entity.WhatsAppImage, jid string) (*entity.WhatsAppImage, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsAppImage, jid)

	if len(ret) == 0 {
		panic("no return value specified for SendImageV2")
	}

	var r0 *entity.WhatsAppImage
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppImage, string) (*entity.WhatsAppImage, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsAppImage, jid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsAppImage, string) *entity.WhatsAppImage); ok {
		r0 = rf(ctx, whatsAppImage, jid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsAppImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsAppImage, string) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsAppImage, jid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, whatsApp
func (_m *WhatsAppUseCase) SendMessage(ctx context.Context, whatsApp *entity.WhatsApp) (*entity.WhatsApp, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsApp)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *entity.WhatsApp
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsApp) (*entity.WhatsApp, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsApp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsApp) *entity.WhatsApp); ok {
		r0 = rf(ctx, whatsApp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsApp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsApp) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsApp)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// SendMessageV2 provides a mock function with given fields: ctx, whatsApp, jid
func (_m *WhatsAppUseCase) SendMessageV2(ctx context.Context, whatsApp *entity.WhatsApp, jid string) (*entity.WhatsApp, *exceptions.CustomerError) {
	ret := _m.Called(ctx, whatsApp, jid)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageV2")
	}

	var r0 *entity.WhatsApp
	var r1 *exceptions.CustomerError
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsApp, string) (*entity.WhatsApp, *exceptions.CustomerError)); ok {
		return rf(ctx, whatsApp, jid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WhatsApp, string) *entity.WhatsApp); ok {
		r0 = rf(ctx, whatsApp, jid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WhatsApp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.WhatsApp, string) *exceptions.CustomerError); ok {
		r1 = rf(ctx, whatsApp, jid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exceptions.CustomerError)
		}
	}

	return r0, r1
}

// NewWhatsAppUseCase creates a new instance of WhatsAppUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWhatsAppUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WhatsAppUseCase {
	mock := &WhatsAppUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
