// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "go.mau.fi/whatsmeow/types"

	whatsmeow "go.mau.fi/whatsmeow"
)

// WhatsAppService is an autogenerated mock type for the WhatsAppService type
type WhatsAppService struct {
	mock.Mock
}

// WhatsAppComposeJID provides a mock function with given fields: jid
func (_m *WhatsAppService) WhatsAppComposeJID(jid string) types.JID {
	ret := _m.Called(jid)

	var r0 types.JID
	if rf, ok := ret.Get(0).(func(string) types.JID); ok {
		r0 = rf(jid)
	} else {
		r0 = ret.Get(0).(types.JID)
	}

	return r0
}

// WhatsAppComposeStatus provides a mock function with given fields: jid, rjid, isComposing, isAudio
func (_m *WhatsAppService) WhatsAppComposeStatus(jid string, rjid types.JID, isComposing bool, isAudio bool) {
	_m.Called(jid, rjid, isComposing, isAudio)
}

// WhatsAppDecomposeJID provides a mock function with given fields: jid
func (_m *WhatsAppService) WhatsAppDecomposeJID(jid string) string {
	ret := _m.Called(jid)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(jid)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// WhatsAppGenerateQR provides a mock function with given fields: qrChan
func (_m *WhatsAppService) WhatsAppGenerateQR(qrChan <-chan whatsmeow.QRChannelItem) (string, int) {
	ret := _m.Called(qrChan)

	var r0 string
	var r1 int
	if rf, ok := ret.Get(0).(func(<-chan whatsmeow.QRChannelItem) (string, int)); ok {
		return rf(qrChan)
	}
	if rf, ok := ret.Get(0).(func(<-chan whatsmeow.QRChannelItem) string); ok {
		r0 = rf(qrChan)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(<-chan whatsmeow.QRChannelItem) int); ok {
		r1 = rf(qrChan)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// WhatsAppIsClientOK provides a mock function with given fields: jid
func (_m *WhatsAppService) WhatsAppIsClientOK(jid string) error {
	ret := _m.Called(jid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(jid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WhatsAppLogin provides a mock function with given fields: jid
func (_m *WhatsAppService) WhatsAppLogin(jid string) (string, int, error) {
	ret := _m.Called(jid)

	var r0 string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, int, error)); ok {
		return rf(jid)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(jid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) int); ok {
		r1 = rf(jid)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(jid)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// WhatsAppLogout provides a mock function with given fields: jid
func (_m *WhatsAppService) WhatsAppLogout(jid string) error {
	ret := _m.Called(jid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(jid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WhatsAppReconnect provides a mock function with given fields: jid
func (_m *WhatsAppService) WhatsAppReconnect(jid string) error {
	ret := _m.Called(jid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(jid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WhatsAppSendText provides a mock function with given fields: ctx, jid, rjid, message
func (_m *WhatsAppService) WhatsAppSendText(ctx context.Context, jid string, rjid string, message string) (string, error) {
	ret := _m.Called(ctx, jid, rjid, message)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, jid, rjid, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, jid, rjid, message)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, jid, rjid, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWhatsAppService creates a new instance of WhatsAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWhatsAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WhatsAppService {
	mock := &WhatsAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
